# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: original

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
